.TH "ZIP_SOURCE_FREE" "3" "April 23, 2006" "NiH" "Library Functions Manual"
.nh
.if n .ad l
.SH "NAME"
\fBzip_source_free\fR
\- free zip data source
.SH "LIBRARY"
libzip (-lzip)
.SH "SYNOPSIS"
\fB#include <zip.h>\fR
.sp
\fIvoid\fR
.br
\fBzip_source_free\fR(\fIstruct zip_source *source\fR);
.SH "DESCRIPTION"
The function
\fBzip_source_free\fR()
frees the zip data source
\fIsource\fR.
If
\fIsource\fR
is
\fRNULL\fR,
it does nothing.
.PP
\fINOTE\fR:
This function should not be called on a
\fIsource\fR
after it was used successfully in a
zip_add(3)
or
zip_replace(3)
call.
.SH "SEE ALSO"
libzip(3),
zip_source_buffer(3),
zip_source_file(3),
zip_source_filep(3),
zip_source_function(3),
zip_source_zip(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
