.TH "ZIP_ADD" "3" "October 6, 2012" "NiH" "Library Functions Manual"
.nh
.if n .ad l
.SH "NAME"
\fBzip_add\fR,
\fBzip_replace\fR
\- add file to zip archive or replace file in zip archive
.SH "LIBRARY"
libzip (-lzip)
.SH "SYNOPSIS"
\fB#include <zip.h>\fR
.sp
\fIzip_int64_t\fR
.br
\fBzip_add\fR(\fIstruct zip *archive\fR,\ \fIconst char *name\fR,\ \fIstruct zip_source *source\fR);
.sp
\fIint\fR
.br
\fBzip_replace\fR(\fIstruct zip *archive\fR,\ \fIzip_uint64_t index\fR,\ \fIstruct zip_source *source\fR);
.SH "DESCRIPTION"
The function
\fBzip_add\fR()
is the obsolete version of
zip_file_add(3).
It is the same as calling
zip_file_add(3)
with an empty
\fIflags\fR
argument.
Similarly, the
\fBzip_replace\fR()
function is the obsolete version of
zip_file_replace(3).
It is the same as calling
zip_file_replace(3)
with an empty
\fIflags\fR
argument.
.SH "SEE ALSO"
libzip(3),
zip_file_add(3),
zip_file_replace(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
