.TH "ZIP_FREAD" "3" "March 10, 2009" "NiH" "Library Functions Manual"
.nh
.if n .ad l
.SH "NAME"
\fBzip_fread\fR
\- read from file
.SH "LIBRARY"
libzip (-lzip)
.SH "SYNOPSIS"
\fB#include <zip.h>\fR
.sp
\fIint\fR
.br
\fBzip_fread\fR(\fIstruct zip_file *file\fR,\ \fIvoid *buf\fR,\ \fIzip_uint64_t nbytes\fR);
.SH "DESCRIPTION"
The
\fBzip_fread\fR()
function reads at most
\fInbytes\fR
bytes from
\fIfile\fR
into
\fIbuf\fR.
.SH "RETURN VALUES"
If successful, the number of bytes actually read is returned.
Otherwise, \-1 is returned.
.SH "SEE ALSO"
libzip(3),
zip_fclose(3),
zip_fopen(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
