.TH "ZIP_RENAME" "3" "June 23, 2012" "NiH" "Library Functions Manual"
.nh
.if n .ad l
.SH "NAME"
\fBzip_rename\fR
\- rename file in zip archive
.SH "LIBRARY"
libzip (-lzip)
.SH "SYNOPSIS"
\fB#include <zip.h>\fR
.sp
\fIint\fR
.br
\fBzip_rename\fR(\fIstruct zip *archive\fR,\ \fIzip_uint64_t index\fR,\ \fIconst char *name\fR);
.SH "DESCRIPTION"
\fBzip_rename\fR()
is the obsolete version of
zip_file_rename(3).
It is the same as calling
zip_file_rename(3)
with an empty flags argument.
.SH "SEE ALSO"
libzip(3),
zip_file_rename(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
