.TH "ZIPCMP" "1" "June 4, 2008" "NiH" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBzipcmp\fR
\- compare contents of zip archives
.SH "SYNOPSIS"
.HP 7n
\fBzipcmp\fR
[\fB\-hiqVv\fR]
\fIzip1\ zip2\fR
.SH "DESCRIPTION"
\fBzipcmp\fR
compares the zip archives
\fIzip1\fR
and
\fIzip2\fR
and checks if they contain the same files, comparing their names,
uncompressed sizes, and CRCs.
File order and compressed size differences are ignored.
.PP
Supported options:
.TP 5n
\fB\-h\fR
Display a short help message and exit.
.TP 5n
\fB\-i\fR
Compare names ignoring case distinctions.
.TP 5n
\fB\-q\fR
Quiet mode.
Compare
\fB\-v\fR.
.TP 5n
\fB\-v\fR
Verbose mode.
Print details about differences to stdout.
(This is the default.)
.TP 5n
\fB\-V\fR
Display version information and exit.
.SH "EXIT STATUS"
\fBzipcmp\fR
exits 0 if the two zip archives contain the same files, 1 if they differ,
and >1 if an error occurred.
.SH "SEE ALSO"
zipmerge(1),
ziptorrent(1),
libzip(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
