.Dd October 1, 2003
.Dt ZIPCMP 1
.Os
.Sh NAME
.Nm zipcmp
.Nd compare contents of zip archives
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl q
.Op Fl V
.Op Fl v
.Ar zip1 zip2
.Sh DESCRIPTION
.\" XXX
.Sh EXIT STATUS
.Nm
exits 0 if the two zip files contain the same files, 1 if they differ,
and \*[Gt]1 if an error occurred.
.Sh SEE ALSO
.\" XXX
.Sh STANDARDS
