.TH "ZIPTORRENT" "1" "July 24, 2008" "NiH" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBziptorrent\fR
\- torrentzip zip archives
.SH "SYNOPSIS"
.HP 11n
\fBziptorrent\fR
[\fB\-hnVv\fR]
\fIarchive\fR\ [\fI...\fR]
.SH "DESCRIPTION"
\fBziptorrent\fR
torrentzips
\fIarchive\fR.
This is a restricted file format used for using bittorrent on zip
files.
Please see
zip_set_archive_flag(3)
for details on what information gets lost through this process.
.PP
Supported options:
.TP 5n
\fB\-h\fR
Display a short help message and exit.
.TP 5n
\fB\-n\fR
Don't actually change archives, just print what would be done.
.TP 5n
\fB\-V\fR
Display version information and exit.
.TP 5n
\fB\-v\fR
Be verbose: print which archives are already torrentzipped and which
need to be rezipped.
.SH "EXIT STATUS"
\fBziptorrent\fR
exits 0 on success and >1 if an error occurred.
.SH "SEE ALSO"
zipcmp(1),
zipmerge(1),
libzip(3)
.SH "AUTHORS"
Dieter Baron <\fIdillo@nih.at\fR>
and
Thomas Klausner <\fItk@giga.or.at\fR>
