/* This file was autogenerated by ./make_zip_err_str.sh from ./zip.h
   -- don't change here */
#include "zip.h"
char *zip_err_str[] = {
    "no error",
    "multi-disk zip-files not supported",
    "replacing zipfile with tempfile failed",
    "closing zipfile failed",
    "seek error",
    "read error",
    "write error",
    "CRC error",
    "containing zip file closed",
    "no such file",
    "file already exists",
    "can't open file",
    "failure to create temporary file",
    "zlib error",
    "malloc failure",
    "entry has been changed",
    "compression method not supported",
    "premature EOF",
};
