name: Solaris
on: [push]
permissions:
  contents: read
jobs:
  Solaris:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: Solaris test
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        usesh: true
        copyback: false
        prepare: |
          python -m venv nihtest-venv
          source nihtest-venv/bin/activate
          pip install nihtest
        run: |
          source nihtest-venv/bin/activate
          cmake -B ${{runner.workspace}}/build ${{github.workspace}}
          cmake --build ${{runner.workspace}}/build --config Release
          ctest --test-dir ${{runner.workspace}}/build --output-on-failure -V -C Release
